db.restaurant.find().pretty()
db.restaurant.find({}, {name:1, _id:1, borough:1, cuisine:1}).pretty()
db.restaurant.find({}, {name:1, _id:0, borough:1, cuisine:1}).pretty()
db.restaurant.find({}, {restaurant_id:1,name:1, _id:0, borough:1,'address.zipcode':1}).pretty()
db.restaurant.find({}, {borough:'Bronx',name:1}).pretty()
db.restaurant.find({}, {borough:'Bronx',address: 1,cuisine:1, grades:1, name:1, name:1,restaurant_id:1}).limit(5).pretty()
db.restaurant.find({},{borough:1,address: 1,cuisine:1, grades:1, name:1,restaurant_id:1}).limit(5).skip(5).pretty()
db.restaurant.find({"grades.score" : {$gt : 90}}).pretty()
db.restaurant.find({"grades.score" : {$lt:100, $gt : 80}}).pretty()
db.restaurant.find({"address.coord": {$gt: -95.754168}}).pretty()
db.restaurant.find({cuisine:{$not:/American/},"grades.score":{$gt : 70}, "address.coord.0": {$gt: -65.754168}}).pretty()
db.restaurant.find({"address.coord.0":{$gt: -65.754168},cuisine:{$not:/American/},"grades.score":{$gt : 70}}).pretty()
db.restaurant.find({cuisine:{$not:/American/}, "grades.grade":"A",borough:{$not:/Brooklyn/}}).pretty()
db.restaurant.find({name:{$regex:/Wil/}},{_id:0,restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
db.restaurant.find({name:{$regex:/ces\b/}},{_id:0,restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
db.restaurant.find({name:{$regex:/Reg/}},{_id:0,restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
db.restaurant.find({$or:[{cuisine:'American '},{cuisine:'Chinese'}],borough:'Bronx'}).pretty()
db.restaurant.find({$or:[{borough:'Staten Island'},{borough:'Queens'},{borough:'Bronx'},{borough:'Brooklyn'}]},{borough:1,restaurant_id:1,_id:0,name:1,cuisine:1}).pretty()
db.restaurant.find({$nor:[{borough:'Staten Island'},{borough:'Queens'},{borough:'Bronx'},{borough:'Brooklyn'}]},{borough:1,restaurant_id:1,_id:0,name:1,cuisine:1}).pretty()
db.restaurant.find({'grades.score':{$lt:10}},{borough:1,restaurant_id:1,_id:0,name:1,cuisine:1}).pretty()
db.restaurant.find({$nor:[{cuisine:'American '},{cuisine:'Chinese'},{name:{$regex:/Wil/}}]},{cuisine:'Seafood',restaurant_id:1,_id:0,borough:1,name:1}).pretty()
db.restaurant.find({$and: [{'grades.grade':'A'},{'grades.score':10}]},{"grades.date": ISODate("2014-08-11T00:00:00Z"),restaurant_id:1,name:1,_id:0,'grades.grade':1,'grades.score':1}).pretty()
db.restaurant.find({$and: [{'grades.1.grade':'A'},{'grades.score':9}]},{"grades.date": ISODate("2014-08-11T00:00:00Z"),restaurant_id:1,name:1,_id:0,'grades.grade':1,'grades.score':1}).pretty()
db.restaurant.find({'address.coord.1':{$gt:42,$lt:52}},{restaurant_id:1, address:1,name:1,'addres.coord':1,_id:0}).pretty()
db.restaurant.find().sort({name:1}).pretty()
db.restaurant.find().sort({name:-1}).pretty()
db.restaurant.find().sort({cuisine:1,borough:-1}).pretty()
db.restaurant.find({'address.street':{$exists:false}}).pretty()
db.restaurant.find({'address.coord':{$type:['double']}}).pretty()
db.restaurant.find({'grades.score':{$mod:[7,0]}},{restaurant_id:1,name:1,'grades.grade':1,_id:0}).pretty()
db.restaurant.find({name:{$regex:/mon/}},{name:1,borough:1,'address.coord':1,cuisine:1,_id:0})
db.restaurant.find({name:{$regex:/^Mad/}},{name:1,borough:1,'address.coord':1,cuisine:1,_id:0}).pretty()


